# Generated by Django 3.1.4 on 2020-12-25 20:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.generate, max_length=10, unique=True),
        ),
    ]
